config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "tasks#index"

  # verb "/path", to: "controller#action"
  get "/tasks", to: "tasks#index"
  get "/task/new", to: "tasks#new"
  get "/task:id", to: "tasks#show", as: "show"
  get "/task/create", to: "tasks#create"
  get "/task/edit", to: "tasks#edit"
  get "/task/destroy", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
        @tasks = Task.all
    end

    def show
        @task = Task.find(params[:id])
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new
        # TODO add ID to create
        @task.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1> My beautiful tasks ☀️ </h1>

<% @tasks.each do |task| %>
    <ul>
    <li> <%= link_to task.title, show_path(task.id) %> </li>
    </ul>
<% end %>

app/views/tasks/new.html.erb
<h1> create new task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h2>Details   : <%= @task.details %></h2>
<h2>Compleated: <%= @task.completed %> </h2>
<%= link_to "Back to tasks", tasks_path %>